import type { MDXComponents } from 'mdx/types';
import {
  Cite,
  Definition,
  Essentials,
  DeepDive,
  Detail,
  Quiz,
  Pearl,
  Pitfall,
  Pediatric,
  Tutorial,
  Controversy,
  RealWorld,
  SpeakerNote,
  AlgorithmDisclaimer,
  TldrCard,
  SourcedFigure,
  Lang,
  Figure,
  BrainCompartments,
  NeurovascularUnit,
  ICPProbePlacement,
  NIRSOptodes,
  TCDWindows,
  PupillaryPathway,
  AutoregLayered,
  AstrupCascadeFig,
  ICPWaveformMorph,
  MarmarouCurve,
  MicrodialysisCatheter,
  PbtO2Probe,
  JugularBulbCatheter,
  ONSDUltrasound,
  EEGMontage,
  EvokedPotentialPathway,
  ECoGStrip,
  RaisedICPLadder,
  NCSEPathway,
  PostArrestProgPathway,
  MxAutoregContrast,
  MxVsPrxArchitecture,
  PrxTimeSeries,
  PrxCppUCurve,
  PrxMxOrx,
  CppoptDoseResponse,
  OrxTrend,
  WidgetEmbed,
} from '@/components/content';
import { Callout, EvidenceLevel, Panel, Card } from '@/components/ui';
import { Mermaid, MermaidPre } from '@/components/content/Mermaid';
import { TableScroll } from '@/components/content/TableScroll';

export const mdxComponents: MDXComponents = {
  Cite,
  Definition,
  Essentials,
  DeepDive,
  Detail,
  Quiz,
  Pearl,
  Pitfall,
  Pediatric,
  Tutorial,
  Controversy,
  RealWorld,
  SpeakerNote,
  AlgorithmDisclaimer,
  TldrCard,
  SourcedFigure,
  Lang,
  Figure,
  BrainCompartments,
  NeurovascularUnit,
  ICPProbePlacement,
  NIRSOptodes,
  TCDWindows,
  PupillaryPathway,
  AutoregLayered,
  AstrupCascadeFig,
  ICPWaveformMorph,
  MarmarouCurve,
  MicrodialysisCatheter,
  PbtO2Probe,
  JugularBulbCatheter,
  ONSDUltrasound,
  EEGMontage,
  EvokedPotentialPathway,
  ECoGStrip,
  RaisedICPLadder,
  NCSEPathway,
  PostArrestProgPathway,
  MxAutoregContrast,
  MxVsPrxArchitecture,
  PrxTimeSeries,
  PrxCppUCurve,
  PrxMxOrx,
  CppoptDoseResponse,
  OrxTrend,
  WidgetEmbed,
  Callout,
  EvidenceLevel,
  Panel,
  Card,
  Mermaid,
  pre: MermaidPre as MDXComponents['pre'],
  table: TableScroll as MDXComponents['table'],
};

export function useMDXComponents(components: MDXComponents): MDXComponents {
  return { ...mdxComponents, ...components };
}
